name: tests
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.x, 1.17.x]
        platform: [ubuntu-latest]
        include:
          # include windows, but only with the latest Go version, since there
          # is very little in the library that is platform specific
          - go-version: 1.x
            platform: windows-latest

          # only update test coverage stats with the most recent go version on linux
          - go-version: 1.x
            platform: ubuntu-latest
            update-coverage: true
    runs-on: ${{ matrix.platform }} 
    
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b #0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: test go code
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ github.token }}
        run: make test